### ISSUE TITLE
Update github-gql-rs published crate version

### ISSUE THREAD

**Issue by deankarn** [github-rs/github-rs#173]
I was recently trying to update some code which uses your `github-gql-rs` crate, contained within this repo, but it looks like due to some dependencies being yanked it can no longer be used.
```
error: failed to select a version for the requirement `untrusted = "^0.5.1"`
  candidate versions found which didn't match: 0.7.0, 0.6.2
  location searched: crates.io index
required by package `rustls v0.11.0`
    ... which is depended on by `hyper-rustls v0.11.0`
    ... which is depended on by `github-gql-rs v0.0.1`
```

it looks like you have updated the dependencies though [here](https://github.com/github-rs/github-rs/blob/master/github-gql-rs/Cargo.toml#L29) but no new release has been published.

Would you be willing to publish a new release 🙏

**Comment by michael-grunder** [comment]
Older issue, but in case others run into this you can just pull from git for now

```toml
[dependencies]
github-gql-rs = { git = "https://github.com/github-rs/github-rs.git", branch = "master" }
```
